apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  # nodePort is the default typ
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30008

  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend